# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping_pong', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='league',
            field=models.ManyToManyField(to='ping_pong.Leagues'),
        ),
    ]
